import { createContext, useContext, useEffect, useState } from "react";

const translations = {
  en: {
    assistantTitle: "Assistant",
    voiceAssist: "Voice Assist",
    voiceNotSupported: "Voice not supported",
    webSpeechEnabled: "Web Speech enabled",
    typePlaceholder: "Type your question...",
    send: "Send",
    languageButton: "Language",
    languageDropdown: "Select language",
    dashboardTitle: "Dashboard",
    patientsTitle: "Patients",
    appointmentsTitle: "Appointments",
    invoicesTitle: "Invoices",
    inventoryTitle: "Inventory",
    inventoryDescription: "Manage supplies, monitor low stock, and restock items when needed.",
    inventoryAddButton: "Add Item",
    inventoryName: "Item",
    inventoryCategory: "Category",
    inventoryQuantity: "Qty",
    inventoryUnit: "Unit",
    inventoryReorderLevel: "Reorder Level",
    inventoryStatus: "Status",
    inventoryActions: "Actions",
    inventoryRestockButton: "Restock",
    inventoryLowStock: "Low Stock",
    inventoryOnHand: "In Stock",
    inventoryItemRequired: "Item name and quantity are required",
    inventoryCreated: "Inventory item created",
    inventoryCreateFailed: "Failed to create inventory item",
    addInventoryItemTitle: "Add Inventory Item",
    inventoryItemNameLabel: "Item Name *",
    inventoryCategoryLabel: "Category",
    inventoryQuantityLabel: "Quantity *",
    inventoryUnitLabel: "Unit",
    inventoryReorderLevelLabel: "Reorder Level",
    inventoryNotesLabel: "Notes",
    restockInventoryTitle: "Restock Item",
    restockQuantityLabel: "Restock Amount",
    inventoryRestockAmountRequired: "Enter a valid restock amount",
    inventoryRestocked: "Inventory restocked successfully",
    inventoryRestockFailed: "Failed to restock inventory",
    noInventoryFound: "No inventory items found",
    save: "Save",
    cancel: "Cancel",
    addPatient: "Add Patient",
    addAppointment: "Add Appointment",
    todayAppointments: "Today's Appointments",
    revenue: "Revenue",
    outstanding: "Outstanding",
    appointmentsTrend: "Appointments Trend",
    upcomingAppointments: "Upcoming Appointments",
    notesTitle: "Notes",
    notesText: "This dashboard shows today’s appointment count, total patients, revenue, unpaid balances, and upcoming bookings.",
    searchPatients: "Search patients...",
    deletePatientConfirm: "Delete this patient?",
    deleteAppointmentConfirm: "Delete this appointment?",
    noPatientsFound: "No patients found",
    noAppointmentsFound: "No appointments found",
    loading: "Loading...",
    botHelp: "Hi! Ask me about appointments, invoices, and patients.",
    botInvoice: "Open the Invoices page or ask for payment details.",
    botAppointment: "Check the Appointments page to schedule or manage bookings.",
    botPatient: "Use the Patients page for records and history.",
    botOutstanding: "Outstanding balance equals treatment cost minus paid amount.",
    botHello: "Hi! I can help with appointments, invoices, patients, and language commands.",
    botNoMatch: "I’m here to help. Ask about appointments, invoices, or patient history.",
    botLanguageChanged: "Language updated.",
    botNavigation: "Taking you where you need to go.",
    patientsColumnName: "Name",
    patientsColumnPhone: "Phone",
    patientsColumnAge: "Age",
    patientsColumnAddress: "Address",
    patientsActions: "Actions",
    patientHistoryButton: "History",
    patientEditButton: "Edit",
    patientDeleteButton: "Delete",
    consultationRequestTitle: "Request Specialist Consultation",
    consultationDescription: "Submit your details to request a consultation with a specialist. Our hospital staff will contact you directly.",
    fullNameLabel: "Full Name *",
    phoneLabel: "Phone Number *",
    emailLabel: "Email (Optional)",
    specialistTypeLabel: "Specialist Type *",
    consultationDetailsLabel: "Consultation Details",
    urgencyLevelLabel: "Urgency Level",
    submitRequest: "Submit Request",
    submitting: "Submitting..."
  },
  es: {
    assistantTitle: "Asistente",
    voiceAssist: "Asistencia de voz",
    voiceNotSupported: "Voz no compatible",
    webSpeechEnabled: "Navegación por voz activada",
    typePlaceholder: "Escribe tu pregunta...",
    send: "Enviar",
    languageButton: "Idioma",
    languageDropdown: "Seleccionar idioma",
    dashboardTitle: "Tablero",
    patientsTitle: "Pacientes",
    appointmentsTitle: "Citas",
    invoicesTitle: "Facturas",
    inventoryTitle: "Inventario",
    inventoryDescription: "Administre suministros, monitoree existencias bajas y reponga artículos cuando sea necesario.",
    inventoryAddButton: "Agregar artículo",
    inventoryName: "Artículo",
    inventoryCategory: "Categoría",
    inventoryQuantity: "Cant.",
    inventoryUnit: "Unidad",
    inventoryReorderLevel: "Nivel de reposición",
    inventoryStatus: "Estado",
    inventoryActions: "Acciones",
    inventoryRestockButton: "Reponer",
    inventoryLowStock: "Bajo stock",
    inventoryOnHand: "En stock",
    inventoryItemRequired: "El nombre y la cantidad del artículo son obligatorios",
    inventoryCreated: "Artículo de inventario creado",
    inventoryCreateFailed: "Error al crear el artículo",
    addInventoryItemTitle: "Agregar artículo de inventario",
    inventoryItemNameLabel: "Nombre del artículo *",
    inventoryCategoryLabel: "Categoría",
    inventoryQuantityLabel: "Cantidad *",
    inventoryUnitLabel: "Unidad",
    inventoryReorderLevelLabel: "Nivel de reposición",
    inventoryNotesLabel: "Notas",
    restockInventoryTitle: "Reponer artículo",
    restockQuantityLabel: "Cantidad a reponer",
    inventoryRestockAmountRequired: "Ingrese una cantidad válida",
    inventoryRestocked: "Inventario repuesto con éxito",
    inventoryRestockFailed: "No se pudo reponer el inventario",
    noInventoryFound: "No se encontraron elementos de inventario",
    save: "Guardar",
    cancel: "Cancelar",
    addPatient: "Agregar paciente",
    addAppointment: "Agregar cita",
    todayAppointments: "Citas de hoy",
    revenue: "Ingresos",
    outstanding: "Pendiente",
    appointmentsTrend: "Tendencia de citas",
    upcomingAppointments: "Próximas citas",
    notesTitle: "Notas",
    notesText: "Este tablero muestra el número de citas de hoy, pacientes totales, ingresos, saldos no pagados y próximas reservas.",
    searchPatients: "Buscar pacientes...",
    deletePatientConfirm: "¿Eliminar este paciente?",
    deleteAppointmentConfirm: "¿Eliminar esta cita?",
    noPatientsFound: "No se encontraron pacientes",
    noAppointmentsFound: "No se encontraron citas",
    loading: "Cargando...",
    botHelp: "¡Hola! Pregúntame sobre citas, facturas y pacientes.",
    botInvoice: "Abre la página de Facturas o pide detalles de pago.",
    botAppointment: "Consulta la página de Citas para programar o administrar reservas.",
    botPatient: "Usa la página de Pacientes para registros e historial.",
    botOutstanding: "El saldo pendiente es el costo del tratamiento menos lo pagado.",
    botHello: "¡Hola! Puedo ayudarte con citas, facturas, pacientes y comandos de idioma.",
    botNoMatch: "Estoy aquí para ayudar. Pregunta sobre citas, facturas o historial de pacientes.",
    botLanguageChanged: "Idioma actualizado.",
    botNavigation: "Te llevo a donde necesitas ir.",
    patientsColumnName: "Nombre",
    patientsColumnPhone: "Teléfono",
    patientsColumnAge: "Edad",
    patientsColumnAddress: "Dirección",
    patientsActions: "Acciones",
    patientHistoryButton: "Historial",
    patientEditButton: "Editar",
    patientDeleteButton: "Eliminar",
    consultationRequestTitle: "Solicitar Consulta con Especialista",
    consultationDescription: "Envíe sus datos para solicitar una consulta con un especialista. Nuestro personal del hospital se pondrá en contacto con usted directamente.",
    fullNameLabel: "Nombre completo *",
    phoneLabel: "Número de teléfono *",
    emailLabel: "Correo electrónico (Opcional)",
    specialistTypeLabel: "Tipo de especialista *",
    consultationDetailsLabel: "Detalles de la consulta",
    urgencyLevelLabel: "Nivel de urgencia",
    submitRequest: "Enviar solicitud",
    submitting: "Enviando..."
  },
  fr: {
    assistantTitle: "Assistant",
    voiceAssist: "Assistant vocal",
    voiceNotSupported: "Voix non prise en charge",
    webSpeechEnabled: "Voix Web activée",
    typePlaceholder: "Tapez votre question...",
    send: "Envoyer",
    languageButton: "Langue",
    languageDropdown: "Choisir une langue",
    dashboardTitle: "Tableau de bord",
    patientsTitle: "Patients",
    appointmentsTitle: "Rendez-vous",
    invoicesTitle: "Factures",
    inventoryTitle: "Inventaire",
    inventoryDescription: "Gérez les fournitures, surveillez les niveaux bas et réapprovisionnez les articles lorsque nécessaire.",
    inventoryAddButton: "Ajouter un article",
    inventoryName: "Article",
    inventoryCategory: "Catégorie",
    inventoryQuantity: "Qté",
    inventoryUnit: "Unité",
    inventoryReorderLevel: "Niveau de réapprovisionnement",
    inventoryStatus: "Statut",
    inventoryActions: "Actions",
    inventoryRestockButton: "Réapprovisionner",
    inventoryLowStock: "Stock bas",
    inventoryOnHand: "En stock",
    inventoryItemRequired: "Le nom et la quantité sont requis",
    inventoryCreated: "Article d'inventaire créé",
    inventoryCreateFailed: "Impossible de créer l'article",
    addInventoryItemTitle: "Ajouter un article d'inventaire",
    inventoryItemNameLabel: "Nom de l'article *",
    inventoryCategoryLabel: "Catégorie",
    inventoryQuantityLabel: "Quantité *",
    inventoryUnitLabel: "Unité",
    inventoryReorderLevelLabel: "Niveau de réapprovisionnement",
    inventoryNotesLabel: "Notes",
    restockInventoryTitle: "Réapprovisionner l'article",
    restockQuantityLabel: "Quantité à réapprovisionner",
    inventoryRestockAmountRequired: "Entrez une quantité valide",
    inventoryRestocked: "Inventaire réapprovisionné avec succès",
    inventoryRestockFailed: "Impossible de réapprovisionner l'inventaire",
    noInventoryFound: "Aucun article d'inventaire trouvé",
    save: "Enregistrer",
    cancel: "Annuler",
    addPatient: "Ajouter un patient",
    addAppointment: "Ajouter un rendez-vous",
    todayAppointments: "Rendez-vous d'aujourd'hui",
    revenue: "Revenu",
    outstanding: "Restant",
    appointmentsTrend: "Tendance des rendez-vous",
    upcomingAppointments: "Prochains rendez-vous",
    notesTitle: "Notes",
    notesText: "Ce tableau affiche le nombre de rendez-vous d'aujourd'hui, le nombre total de patients, les revenus, les soldes impayés et les prochaines réservations.",
    searchPatients: "Rechercher des patients...",
    deletePatientConfirm: "Supprimer ce patient?",
    deleteAppointmentConfirm: "Supprimer ce rendez-vous?",
    noPatientsFound: "Aucun patient trouvé",
    noAppointmentsFound: "Aucun rendez-vous trouvé",
    loading: "Chargement...",
    botHelp: "Bonjour ! Demandez-moi des informations sur les rendez-vous, factures et patients.",
    botInvoice: "Ouvrez la page Factures ou demandez les détails de paiement.",
    botAppointment: "Consultez la page Rendez-vous pour planifier ou gérer les réservations.",
    botPatient: "Utilisez la page Patients pour les dossiers et l'historique.",
    botOutstanding: "Le solde restant est le coût du traitement moins le montant payé.",
    botHello: "Bonjour ! Je peux vous aider avec les rendez-vous, factures, patients et commandes de langue.",
    botNoMatch: "Je suis là pour aider. Demandez des rendez-vous, factures ou historique patient.",
    botLanguageChanged: "Langue mise à jour.",
    botNavigation: "Je vous amène là où vous devez aller.",
    patientsColumnName: "Nom",
    patientsColumnPhone: "Téléphone",
    patientsColumnAge: "Âge",
    patientsColumnAddress: "Adresse",
    patientsActions: "Actions",
    patientHistoryButton: "Historique",
    patientEditButton: "Modifier",
    patientDeleteButton: "Supprimer",
    consultationRequestTitle: "Demander une Consultation Spécialiste",
    consultationDescription: "Soumettez vos coordonnées pour demander une consultation avec un spécialiste. Notre personnel hospitalier vous contactera directement.",
    fullNameLabel: "Nom complet *",
    phoneLabel: "Numéro de téléphone *",
    emailLabel: "Email (Optionnel)",
    specialistTypeLabel: "Type de spécialiste *",
    consultationDetailsLabel: "Détails de la consultation",
    urgencyLevelLabel: "Niveau d'urgence",
    submitRequest: "Soumettre la demande",
    submitting: "Soumission..."
  }
};

const languages = {
  en: { label: "English", code: "en" },
  es: { label: "Español", code: "es" },
  fr: { label: "Français", code: "fr" }
};

const LanguageContext = createContext({});

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("en");

  useEffect(() => {
    const stored = window.localStorage.getItem("appLanguage");
    if (stored && translations[stored]) {
      setLanguage(stored);
    }
  }, []);

  useEffect(() => {
    window.localStorage.setItem("appLanguage", language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, languages, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
